<a href="https://colab.research.google.com/github/Yuliana-Lestari/data-science-2026/blob/main/Pertemuan2_YulianaLestari_250401020199.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS Data Science - Universitas Siber Asia
* **Nama Lengkap:** Yuliana Lestari
* **NIM:** 250401020199
* **Kelas:** IF403

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [3]:
df.shape

(891, 12)

Q1 : Dataset memiliki 891 baris dan 12 kolom

In [4]:

df.isnull().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


Q2 : Kolom Age, Cabin, dan Embarked memiliki missing values

In [5]:
# Q3 — Persen yang selamat
df['Survived'].mean()*100

np.float64(38.38383838383838)

Q3 : Sekitar 38% penumpang selamat

In [6]:
# Q4 — Wanita kelas 1
wk1 = df[(df['Sex']=='female') & (df['Pclass']==1)]

len(wk1)
wk1['Age'].mean()

np.float64(34.61176470588235)

Q4 : Jumlah wanita kelas 1 sekitar 94 orang dengan rata-rata usia sekitar 34 tahun

In [7]:
# Q5 — Survival per kelas
df.groupby('Pclass')['Survived'].mean()

,Survived
Pclass,
1,0.629630
2,0.472826
3,0.242363


Q5 : Kelas 1 memiliki tingkat keselamatan tertinggi

In [8]:
# Q6 — Analisis tambahan
df.groupby('Sex')['Survived'].mean()

,Survived
Sex,
female,0.742038
male,0.188908


Q6 : Wanita memiliki peluang selamat lebih tinggi dibanding pria

In [9]:
# Membuat list
data = [10, 20, 'Python', True, 3.14]

# Akses & slicing
print(data[0])
print(data[-1])
print(data[1:3])

# Manipulasi
data.append(99)
data.insert(1, 55)
data.remove(20)

print(data)

10
3.14
[20, 'Python']
[10, 55, 'Python', True, 3.14, 99]


In [10]:
#Tuple
koord = (10.5, -6.8, 'Jakarta')
print(koord[0])

10.5


In [11]:
# Membuat dictionary
mahasiswa = {
    'nama': 'Yuliana Lestari',
    'nim': '250401020199',
    'prodi': 'Informatika',
    'ipk': 3.44
}

# Akses nilai
print(mahasiswa['nama'])
print(mahasiswa.get('usia', 0))   # default jika key tidak ada

# Update dan hapus
mahasiswa['angkatan'] = 2025      # tambah key baru

# Hapus key dengan aman
if 'nim' in mahasiswa:
    del mahasiswa['nim']

# Tampilkan hasil akhir
print(mahasiswa)

Yuliana Lestari
0
{'nama': 'Yuliana Lestari', 'prodi': 'Informatika', 'ipk': 3.44, 'angkatan': 2025}


In [12]:
# set
a = {1, 2, 3}
b = {3, 4, 5}

print(a & b)
print(a | b)

{3}
{1, 2, 3, 4, 5}


In [13]:
import numpy as np

# Dari list Python
a1D = np.array([1, 2, 3, 4, 5])
a2D = np.array([[1,2,3],[4,5,6]])

print("a1D:", a1D)
print("a2D:\n", a2D)

# Array dengan nilai inisial
zeros = np.zeros((3, 4))
ones  = np.ones((2, 3))
eye   = np.eye(4)
full  = np.full((2, 2), 7)

print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity:\n", eye)
print("\nFull:\n", full)

# Sequence
arange = np.arange(0, 20, 2)
linsp  = np.linspace(0, 1, 11)

print("\nArange:", arange)
print("\nLinspace:", linsp)

# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(5,))  # diperkecil biar tidak panjang

print("\nRandom Integer:\n", rand_int)
print("\nRandom Float:\n", rand_flt)

a1D: [1 2 3 4 5]
a2D:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Full:
 [[7 7]
 [7 7]]

Arange: [ 0  2  4  6  8 10 12 14 16 18]

Linspace: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

Random Integer:
 [[ 8 77 65 43]
 [43 85  8 69]
 [20  9 52 97]]

Random Float:
 [ 0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797]


In [14]:
import numpy as np

# Buat random generator
rng = np.random.default_rng(42)

# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a + b:", a + b)
print("a * b:", a * b)
print("a^2:", a ** 2)

# Universal functions (ufuncs)
print("\nAkar:", np.sqrt(a))
print("Exp:", np.exp(a))
print("Log:", np.log(b))

# Fungsi statistik
data = rng.normal(0, 1, 1000)

print("\nMean:", round(np.mean(data), 4))
print("Std :", round(np.std(data), 4))
print("Min :", round(np.min(data), 4))
print("Max :", round(np.max(data), 4))
print("Q1  :", round(np.percentile(data, 25), 4))
print("Q3  :", round(np.percentile(data, 75), 4))

a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
a^2: [ 1  4  9 16 25]

Akar: [1.         1.41421356 1.73205081 2.         2.23606798]
Exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Log: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]

Mean: -0.0289
Std : 0.9887
Min : -3.6484
Max : 3.1789
Q1  : -0.6963
Q3  : 0.5899


In [15]:
# Python — Pandas Series
import pandas as pd
import pandas as pd

# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])

# Series dengan index kustom
nilai = pd.Series(
    [85, 92, 78, 95],
    index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob'])     # → 92
print(nilai[nilai>80])  # filter
print(nilai.mean())     # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


In [16]:
#  Python — Membuat Pandas DataFrame
 # Membuat DataFrame dari dictionary
data = {
    'nama':  ['Ali','Budi','Caca','Dina'],
    'usia':  [22, 25, 21, 23],
    'kota':  ['Jakarta','Bandung','Surabaya','Medan'],
    'ipk':   [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)

# Informasi dasar
print(df.shape)    # → (4, 4)
print(df.dtypes)   # tipe data per kolom
print(df.columns)  # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [17]:
# Python — pd.read_csv()
import pandas as pd

# Load dataset Titanic
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Eksplorasi data
print("5 data pertama:")
print(df.head())

print("\nInfo data:")
df.info()

print("\nStatistik deskriptif:")
print(df.describe())

5 data pertama:
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   N

In [18]:
# Python — Boolean Indexing
import pandas as pd

# Load dataset Titanic (URL lengkap)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Filter satu kondisi
penumpang_selamat = df[df['Survived'] == 1]
penumpang_wanita  = df[df['Sex'] == 'female']

print("Jumlah penumpang selamat:", len(penumpang_selamat))
print("Jumlah penumpang wanita:", len(penumpang_wanita))

# Filter kondisi ganda (& = AND, | = OR)
wanita_kelas1 = df[(df['Sex']=='female') & (df['Pclass']==1)]

print("\nWanita kelas 1:")
print(wanita_kelas1.head())

# Seleksi kolom tertentu
print("\nKolom tertentu:")
print(df[['Name','Age','Sex','Survived']].head())

Jumlah penumpang selamat: 342
Jumlah penumpang wanita: 314

Wanita kelas 1:
    PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
11           12         1       1   
31           32         1       1   
52           53         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
31     Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
52           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   

    Parch    Ticket      Fare Cabin Embarked  
1       0  PC 17599   71.2833   C85        C  
3       0    113803   53.1000  C123        S  
11      0    113783   26.5500  C103        S  
31      0  PC 17569  146.5208   B78        C

In [19]:
import pandas as pd

# Pastikan dataset sudah ada
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Pola dasar: groupby → aggregation
print(df.groupby('Pclass')['Survived'].mean())

# Agregasi multiple kolom & fungsi
hasil = df.groupby('Pclass').agg(
    total      = ('PassengerId', 'count'),
    selamat    = ('Survived', 'sum'),
    pct_selamat= ('Survived', 'mean'),
    rata_usia  = ('Age', 'mean'),
    max_fare   = ('Fare', 'max')
)

hasil = hasil.round(3)
print("\nHasil agregasi:")
print(hasil)

# GroupBy multi-kolom (diperbaiki tanpa backslash)
multi = df.groupby(['Pclass','Sex'])['Survived'].mean().unstack().round(3)

print("\nGroupBy Pclass & Sex:")
print(multi)

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Hasil agregasi:
        total  selamat  pct_selamat  rata_usia  max_fare
Pclass                                                  
1         216      136        0.630     38.233   512.329
2         184       87        0.473     29.878    73.500
3         491      119        0.242     25.141    69.550

GroupBy Pclass & Sex:
Sex     female   male
Pclass               
1        0.968  0.369
2        0.921  0.157
3        0.500  0.135


### Kesimpulan Praktikum (Pertemuan 2)

  Pada pertemuan ini, saya mempelajari struktur data bawaan Python (list, tuple, dictionary, dan set) beserta karakteristik penggunaannya. Selain itu, saya juga mempelajari dasar komputasi numerik menggunakan library NumPy (ndarray) serta teknik manipulasi dan analisis data tabular menggunakan library Pandas (Series dan DataFrame).

  1. NumPy terbukti jauh lebih efisien dan cepat (10 hingga 100 kali lipat) dibandingkan list Python standar untuk operasi numerik karena mendukung fitur vektorisasi tanpa loop eksplisit.
  2. Pandas DataFrame sangat andal untuk mengelola data heterogen berlabel (seperti file CSV), serta mempermudah analisis data melalui teknik boolean indexing, filtering (.loc/.iloc), dan operasi manipulasi kelompok (groupby dan agregasi).
  3. Berhasil menerapkan library Pandas untuk memuat, mengeksplorasi secara deskriptif, dan melakukan penyaringan kondisi pada dataset publik klasik seperti data penumpang Titanic.

  Mengingat dataset di dunia nyata seringkali memiliki banyak baris kosong (missing values) dan tipe data yang tidak konsisten saat dimuat lewat pd.read_csv(), apa saja fungsi bawaan Pandas yang paling efisien untuk melakukan pembersihan data (data cleaning) sebelum data tersebut siap diolah ke dalam fungsi statistik NumPy atau pemodelan?